echo "Kopiere Datei ins Setupverzeichnis 32-Bit"
copy /y /v Win32\Release\PCMDEVManager.exe "e:\Inno\Setupfiles\Programme\PCMDEVManager"
copy /y /v Win32\Release\PCMDEVManager.DE "e:\Inno\Setupfiles\Programme\PCMDEVManager"
copy /y /v Win32\Release\PCMDEVManager.EN "e:\Inno\Setupfiles\Programme\PCMDEVManager"
echo "Kopiere Datei ins Setupverzeichnis 64-Bit"
copy /y /v Win64\Release\PCMDEVManager.exe "e:\Inno\Setupfiles\Programme\PCMDEVManager_x64"
copy /y /v Win64\Release\PCMDEVManager.DE "e:\Inno\Setupfiles\Programme\PCMDEVManager_x64"
copy /y /v Win64\Release\PCMDEVManager.EN "e:\Inno\Setupfiles\Programme\PCMDEVManager_x64"

echo "Kopiere Doku ins Setupverzeichnis"
copy /y /v PCMDEVManager.docx "e:\Inno\Setupfiles\Programme\PCMDEVManager"
copy /y /v PCMDEVManager.pdf "e:\Inno\Setupfiles\Programme\PCMDEVManager"
copy /y /v PCMDEVManager.htm "e:\Inno\Setupfiles\Programme\PCMDEVManager"
